server:
  port: 8083

spring:
  application:
    name: shipping-service

  datasource:
    url: jdbc:postgresql://localhost:5432/shipping_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: shipping-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: io.github.etr.playground.shipping.infra.StockReservedKafkaListener.StockReserved
        spring.json.trusted.packages: io.github.etr.playground
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  modulith:
    events:
      externalization:
        enabled: true
        kafka:
          enabled: true

management:
  endpoints.web.exposure.include: '*'
  endpoint.prometheus.enabled: true
  tracing:
    sampling:
      probability: 1.0  # 100% sampling for dev (lower in prod)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  observations:
    annotations:
      enabled: true

logging:
#  level:
#    org.springframework.kafka: DEBUG
#    org.springframework.messaging: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"