input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  # Add Kubernetes/Docker fields later if needed
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
