server:
  port: 8082

inbox.relay.delay.ms: 100

spring:
  application:
    name: inventory-service

management:
  endpoints.web.exposure.include: '*'
  endpoint.prometheus.enabled: true
  tracing:
    sampling:
      probability: 1.0  # 100% sampling for dev (lower in prod)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  observations:
    annotations:
      enabled: true

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
#  level:
#    io.micrometer.tracing: DEBUG