server:
  port: 8084

spring:
  application:
    name: shipping-ui

shipping:
  service:
    url: http://localhost:8083

vaadin:
  servlet:
    production-mode: false

management:
  endpoints.web.exposure.include: '*'
  endpoint.prometheus.enabled: true
  tracing:
    sampling:
      probability: 1.0  # 100% sampling for dev (lower in prod)
  observations:
    annotations:
      enabled: true

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"